### PR TITLE
Automatic filling of discriminator column.

### PR DESCRIPTION
**Pull request by gausie**
This seems to work but you know more about the correct structure than I do.

### CODE REVIEW

**Comment by gausie** [comment]
How else could you use it?

**Comment by rydurham** [comment]
My original use case involved storing the model data to the database with a default discriminator value, and then only using STI when reading the data back from the database.  I have not yet had need to directly instantiate a child entity.

**Comment by gausie** [comment]
But then how would anything be cast as anything other than the default?

**Comment by rydurham** [comment]
In my original scenario, when updating the model a new discriminator value could be set, at which point  the cache was flushed and when the user was redirected back to the page showing the model object it would be re-instantiated as the new class type.

**Comment by gausie** [comment]
Clearing this from my outstanding PRs sorry!

**Pull request closed without merging**
